### ISSUE TITLE
持ち時間制御

### ISSUE THREAD

**Issue by convex2000** [HiraokaTakuya/apery_rust#2]
持ち時間ありの対局にも対応してほしいです。

**Comment by HiraokaTakuya** [comment]
持ち時間ありの対局には対応しています。もし問題があるなら詳細を教えて頂きたいです。

**Comment by convex2000** [comment]
例えば持ち時間:5分 秒読み:5秒のとき、初手から5秒固定しか使ってくれません。とくに秒読みなしのとき常に0秒指しです。ShogiGUI使ってます。

**Comment by HiraokaTakuya** [comment]
ありがとうございます。持ち時間あり かつ 秒読みあり の時に問題がありますね。修正対応します。
